--- # Create ec2 instance playbook

  - hosts: localhost
    connection: local
    gather_facts: false
    #vars:
    # keypair: 2nd-i
    # instance_type: t2.micro
    # image: 
    # group: default
      # region: ap-south-1a
      #instance_name: ansi-ec2
    tasks:
     - name: ec2 instance creating
       ec2_instance:
         image: 
         instance_type: t2.micro
         instance_tags: ansi-ec2
         keypair: 2nd-i
         region: ap-south-1
         gruop: default
         wait: true
         wait_timeout: 300
       register: ec2_info

     - name: Add instances to host group
       add_host: hostname={{ item.public_ip }} groupname=ec2hosts
       with_items: ec2_info.instances

     - name: Wait for SSH to come up
       wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
       with_items: ec2_info.instances
